[feat] h2의 FTsearch 적용한 메소드 적용
codestates-seb/seb39_main_023 pull request #40
Opened 2022-09-21 09:17 UTC by wonyong92

2022-09-21 14:52 UTC, Hyune-c requested changes

2022-09-21 14:52 UTC, Hyune-c commented on server/mainPr/src/main/java/com/team23/mainPr/Domain/RentPost/Controller/RentPostController.java
> +    @PostMapping("/ftSearch")
무슨 기능을 하는지 전혀 추측되지 않습니다.
심지어 swagger 주석도 없네요.

h2 에 있는 기능을 명시했나본데.. 이걸 왜 사용자가 알아야되죠?

2022-09-21 14:52 UTC, Hyune-c commented on server/mainPr/src/main/java/com/team23/mainPr/Domain/RentPost/Service/RentPostService.java
> +        rentPostRepository.ftSearch(""+phrase+"")
phrase 는 이미 string 인데 "" 가 의미 있나요?

2022-09-21 14:52 UTC, Hyune-c commented on server/mainPr/src/main/java/com/team23/mainPr/Domain/RentPost/Service/RentPostService.java
> +        return result;
3줄로 표현된 이 메서드는 한줄로 표현할 수 있습니다.

2022-09-21 22:31 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Domain/RentPost/Controller/RentPostController.java
> +    @PostMapping("/ftSearch")
친절하지 못했습니다 ㅠ 단순히 기능 구현해서 테스트 해볼 생각에만 빠져서 설명이나 명확도가 떨어지게 작성된 것 같습니다. 수정하겠습니다.

2022-09-21 22:31 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Domain/RentPost/Service/RentPostService.java
> +        rentPostRepository.ftSearch(""+phrase+"")
문자열이 네이티브 쿼리 sql에서 인식이 안되어 별도로 따옴표를 넣었습니다. - 빼면 스트링 인식이 안됨 ㅠ

2022-09-21 22:31 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Domain/RentPost/Service/RentPostService.java
> +        return result;
리팩토링 하겠습니다. collect 함수 사용하도록 하겠습니다.

2022-09-21 23:01 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Domain/RentPost/Service/RentPostService.java
> +        rentPostRepository.ftSearch(""+phrase+"")
sql문에서 파라미터 양쪽으로 공백을 넣으니 정상 작동하였습니다;;;;. 따옴표 추가하는 부분을 삭제하였습니다 .

2022-09-22 00:07 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Domain/RentPost/Service/RentPostService.java
> +        return result;
RentPostRepository 의 쿼리 수행 메서드의 응답 결과를 List<Object> 가 아닌 List<RentPost>로 바로 엔티티로 맵핑이 되도록 하였고, collect 함수를 사용하여 한번에 응답할 수 있도록 리팩토링 하였습니다.

2022-09-22 04:02 UTC, merged