[Feat] 로그인, 로그인 상태 유지 등
codestates-seb/seb39_main_023 pull request #50
Opened 2022-09-27 00:29 UTC by Moondoyeon

env로 서버주소 곧 가리겠습니다!!!

2022-09-27 14:43 UTC, wlgns2223 requested changes

2022-09-27 14:43 UTC, wlgns2223 commented on client/src/components/LoginInput/LoginInput.tsx
> +            axios.defaults.headers.common['Authorization'] = `Bearer ${token}`;
1. 서버주소가 노출되어 있네요 
2. withCredentials: false 설정을 하고 request header에 베어러 토큰을 담아보내면 CORS에러가 안뜨던가요?

2022-09-27 14:43 UTC, wlgns2223 commented on client/src/components/Modal/UserModal.tsx
> +        localStorage.clear();
애플리케이션을 사용하다보면 localStorage에 여러 값들을 저장 할 수 있는데 localStorage를 다 clear해버리기보다 
지우고자하는 값의 키를 이용해서 해당 값만 지워주도록 하세요.

2022-09-28 02:00 UTC, Moondoyeon commented on client/src/components/LoginInput/LoginInput.tsx
> +            axios.defaults.headers.common['Authorization'] = `Bearer ${token}`;
1. 넵 충현님이 dotenv 관련 코드를 작성하셔서 해당 코드가 front 브랜치에 머지 되면 그때 풀받아서 수정하고자 했습니다!!! 오늘 그 작업 진행하고자 합니다 ㅠ! 
2. 넵.. cors 관련해서 오늘 백엔드 분과 논의 후에 특정오리진에대한 cors설정 처리하겠습니다.!

2022-09-28 02:00 UTC, Moondoyeon commented on client/src/components/Modal/UserModal.tsx
> +        localStorage.clear();
넵! 알겠습니다~

2022-09-28 08:47 UTC, merged