세번째 PR 제출
codestates-seb/seb39_main_023 pull request #6
Opened 2022-09-14 06:57 UTC by wonyong92

2022-09-15 14:32 UTC, Hyune-c requested changes
수고하셨습니다.

2022-09-15 22:49 UTC, wonyong92 reviewed
이외에 수정해야할 사항 
1. 클래스 네이밍이 이상했는데 다시 확인해서 명확하고 통일성 있게 수정하겠습니다.
   - 명사형으로 네이밍, 연관되는 클래스가 있을 경우 가능한 대칭이 되는 접두사,접미어 사용, 지금은 도저히 네이밍 센스가 없어 조금은 길게라도 클래스 기능 표현에 집중하기.
2. Common dto의 경우 제네릭에 extends 가 아닌 Super를 사용하는 것이 더욱 명확한 표현
    - 다시 코드 확인해보니 super {parent.class} 의 경우 parent와 parent의 상위 클래스를 사용가능하게 하는 제네릭 타입이라 지금 처럼 extends {parent.class} 를 사용해서 parent와 parent를 상속하는 클래스만 허용하는 방식을 그대로 사용해야 할것 같은데 조금 더 찾아보고 코드를 리팩토링하겠습니다 ㅠ
3. EOF에 NewLine? 정확한 표현인지 다시 찾아보고 명확하게 작성하기
   - 좀 더 명확하게 수정완료
5. Readme에서 커스텀한 주석 컨벤션을 제거하고, JavaDoc 기반으로 다시 컨벤션 만들기
   - 태그 설명 추가 완료!
7. JWT 시그니쳐 키는 이후 프로젝트 마무리전에 꼭 보안 설정하기
   - 꼭 확인하기...
9. 코드 작성하고 바로 PR하지 않고 하루 정도 지난 다음에 내가 내 코드 리뷰하고 그 다음에 PR 작성하기
    - 하루 지나고 다시 읽어본 제 코드는 똥이었.....
10. 테스트 코드는 정말 최대한 가독성을 높이기 위해 노력하기(한글 메소드까지 허용, Display 어노테이션으로 한번에 설명하기)
11. 메소드 응답 빨리 회의해서, 응답 메세지("true" 이런거 좋지 않음) 수정하기
    - TIME ZONE 설정에 필요한 ZoneId , 응답 메세지(String)을 enum 클래스 작성으로 상수를 이용하도록 하였습니다.
12. 현재 토큰이나 로그인 정보를 서버에 저장하지 않는 상태 - DB를 이용하거나, 별도로 로그인 정보를 저장하는 객체(컬렉션)를 생성(세션 규칙 필요:만료,암호화)하여 세션을 구성하기.
    - 생각해보니 지금 토큰에는 단순히 DB에서 유저 PK만 들어가있어서 DB에서 다시 유저 정보, 로그인 상태를 가지고 오는 방식을 취하고 있는데 반쯤 세션의 개념이 적용된 것 같기도 하고 ;;; 세션을 어떻게 구성하는지 찾아보고 적용하겠습니다 ㅠ
13. 코드 반복 줄이기
    - 리턴문들, 에러처리 부분 확 줄였습니다! 소나린트도 적용해보았습니다!
14. .get() 쓰지 않기 - 코드 테스트 중에도 이상한 데이터가 할당되는 문제가 있었다. 
    - 해당하는 방식을 쓴 코드들 모두 수정하였습니다!
15. 소나린트 활용해보기!
    - 적용해서 리팩토링해보았습니다!

모두 수정 적용해서 다시 도전하겠습니다 ㅠ

2022-09-15 22:49 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/CommonService/CommonService.java
> +@Service
```@Service```의 경우에는 ```@Component```와 기능 상 큰 차이점은 없지만 레이어 구분을 위하여 사용하고
```@Repository```의 경우 쿼리 메소드의 에러를 Spring DataAccessException으로 변환하는 기능까지 포함된 어노테이션 입니다.
```@RestController```의 경우 ```@Controller```에 ```@ResponseBody```가 기본적으로 적용되는 어노테이션으로 data를 반환하기 위해 사용되며 ```@Controller```는 view를 반환하기 위한 어노테이션입니다.

지금처럼 json data를 ResponsEntity를 통해 생성하고 반환한다면, ```@Controller```에 ```@ResponseBody```를 사용하는게 좀 더 컨트롤러의 기능을 명확하게 표현할 수 있습니다.

2022-09-15 22:49 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Member/Dto/CreateMemberDto.java
>      @ApiModelProperty(value = "패스워드 - 특수문자 [@!#%&] 최소 1글자 이상 포함, 최소 6글자 최대 20 글자 ", example = "password@@@password")
회원가입할 때 중복확인, 문자열 패턴 검사 등의 기능을 넣은 별도의 메소드를 서비스 레이어에서 사용하려고 합니다.(현재는 문자열 패턴 검사만 적용된 loginValidation 메소드를 구현해놓은 상태입니다.) 
스웨거 설명은 api문서에서 프론트엔드에 dto(회원가입에 필요한 데이터의 제한? 조건?) 설명이 필요할 것 같아서 작성해봤습니다 ㅎ

2022-09-15 22:49 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/RentPost/Controller/RentPostController.java
> +@RestController
몇 번을 사용 했는데도 그냥 쓰다보니 차이도 모르고 사용하고 있었네요 (--;;;;)

2022-09-15 22:49 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/RentPost/Controller/RentPostController.java
> +    @ApiOperation(value = "렌트 물품 게시글 등록.", notes = "데이터베이스에 물품 렌트 글을 생성하고, 생성된 게시글 데이터를 응답한다.")
최신 버전의 swagger를 사용하도록 하겠습니다 ㅎ 코드 작성을 해놓고 리뷰를 쉽게할 방법을 찾으려고 swagger hub에 인텔리제이에서 생성된 코드를 사용하려고 하니 최신버전(open api v3)이 아니라서 뭔가 계속 컨버팅이 필요하길래 이상함을 느꼈습니다 ㅠ

2022-09-15 22:49 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/RentPost/Controller/RentPostController.java
> +            return new ResponseEntity(response, HttpStatus.INTERNAL_SERVER_ERROR);
반복되는 리턴 부분, 깔끔하게 처리하도록 하겠습니다!

2022-09-15 22:49 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Swagger/SwaggerConfig.java
> +     * */
javadoc 형식 찾아보고 바로 적용하겠습니다!

2022-09-15 22:49 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Swagger/SwaggerConfig.java
> +    UiConfiguration uiConfig() {
접근 제한자를 사용하여 빈을 생성하는 메소드를 불필요하게 접근할 수 없도록 하는게 맞는것 같습니다. 다른 코드에서도 접근제한자가 올바르게 지정되지 않았는지 확인해보겠습니다

2022-09-16 03:51 UTC, wonyong92 reviewed
주요한 리팩토링 지점에 코맨트를 생성하였습니다!

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/test/java/com/team23/mainPr/MainPrApplicationTests.java
> +        assertThat(dto.getNickname()).as("check user Nickname").isEqualTo(nickname);
AssertJ 적용 완료!

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/test/java/com/team23/mainPr/MainPrApplicationTests.java
> +    @DisplayName(value = "회원가입 기능 테스트 = 응답의 아이디,비밀번호, 닉네임 검증")
한번에 테스트 내용 확인 할 수 있게 설명 추가!

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/CommonService/MemberIdExtractorFromJwt.java
> + * @see <a href="https://velopert.com/2389">jwt 생성 참고</a>
javaDoc 형식의 주석문으로 교체 완료!

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/CustomException/CustomException.java
> +    private final ErrorData errordata;
접근 제한자 변경!

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Dto/ChildCommonDto.java
> +    HttpStatus httpStatus;
ChildCommonDto 로 이름 변경, 상속하는 클래스도 ParentCommonDto 로 이름 변경
컨트롤러 레이어에서 한번에 ResponseEntity를 만들기 위해 status 코드 저장 필드 생성. body에는 필요없으니까 JsonIgnore 추가!

null인 데이터는 리턴하고 싶지 않아서 JsonInclude(JsonInclude.Include.NON_NULL)로 jackson 설정 변경

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Enum/ChildCommonDtoMsgList.java
> +public enum ChildCommonDtoMsgList {
ChildCommonDto에 사용될 msg의 리스트를 enum으로 관리!

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Enum/TimeZone.java
> +    ASIA_SEOUL("Asia/Seoul");
타임존 설정을 위한 ZoneId 목록을 enum으로 관리

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Jwt/Service/JwtBuilder.java
> +        return JWT.create()
불필요한 필드 선언 제거!

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Login/Controller/LoginController.java
> +@Controller
ResponseBody를 사용하고 있으므로 Controller로 변경!

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Login/Dto/DoLoginDto.java
> +    private String loginId;
게터,세터가 존재하므로 private로 접근 제한자 설정

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Login/Service/LoginService.java
> +    private final JwtBuilder jwtService;
서비스가 아니므로 명확한 이름으로 변경!

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Login/Service/LoginService.java
> +                    String token = jwtService.buildJwt(member);
삭제 가능한 부분;;; 다시 수정 예정

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Login/Service/LoginService.java
> +            return new ChildCommonDto(ERROR.getMsg(), HttpStatus.INTERNAL_SERVER_ERROR, null);
서비스 레이어에서 응답에 필요한 데이터를 한번에 만들어서 보내기

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/MainPrApplication.java
> +    }    public static final ZoneId DEFAULT_TIME_ZONE = ASIA_SEOUL.getZoneId();
모든 코드에 동시에 적용되는 데이터라서, 전역 변수를 사용해보았습니다!

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Member/Controller/MemberController.java
> +import io.swagger.v3.oas.annotations.Operation;
스웨거 버전 업! 사용되는 어노테이션이 변경되었습니다

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Member/Controller/MemberController.java
> +        ChildCommonDto response = memberService.loginValidation(dto);
응답에 필요한 모든 데이터를 가진 ChildCommonDto 를 서비스레이어에서 응답합니다!

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Member/Dto/CreateMemberDto.java
> +@ApiModel(value = "CreateMemberDto", description = "입력 받은 회원 가입 정보를 dto로 맵핑")
모호한 설명이라 정보 추가!

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Member/Service/MemberService.java
> +            Member member = memberRepository.findById(memberId).orElse(null);
.get() 함수 제거!

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Profile/Dto/UpdateProfileDto.java
> +public class UpdateProfileDto {
클래스 네이밍 형식을 통일(메소드명+엔티티+Dto)

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Profile/Mapper/ProfileMapper.java
> +    ProfileMappedDto ProfileToProfileResponse(Profile profile);
응답을 위해 맵핑되는 클래스명은 (필드명+MappedDto)로 통일

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/Profile/Service/ProfileService.java
> +    public ChildCommonDto getProfile(Integer postId) {
상속이 반드시 필요한 클래스라서 Child 접두사 이용!

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/RentPost/Dto/RentPostResponse.java
> +public class RentPostResponse extends ParentCommonDto {
아 네이밍이 마음에 안드는데;; 수정하겠습니다 ㅠ

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/RentPost/Entity/RentPost.java
> +    private ZonedDateTime writeDate = ZonedDateTime.now(DEFAULT_TIME_ZONE);
전역 변수를 이용해서 여러곳에서 한번에 국가 설정 변경가능

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/test/java/com/team23/mainPr/MainPrApplicationTests.java
> +    @DisplayName(value = "회원가입 입력 데이터 유효성 검증 기능 테스트 = 성공/실패 검증")
명확한 테스트 기능 설명!

2022-09-16 03:51 UTC, wonyong92 commented on server/mainPr/src/test/java/com/team23/mainPr/MainPrApplicationTests.java
> +        assertThat(dto.getMsg()).as("check user ID, password").isEqualTo(TRUE.getMsg());
AssertJ 적용!

2022-09-16 03:53 UTC, wonyong92 commented on server/mainPr/src/main/java/com/team23/mainPr/CommonService/MemberIdExtractorFromJwt.java
> +@Component
Service가 아닌 (서비스 레이어로 제한 X)단독으로 사용될 빈! -> Component 로 변경!

2022-09-16 05:03 UTC, Hyune-c commented on server/mainPr/src/test/java/com/team23/mainPr/MainPrApplicationTests.java
> +        assertThat(dto.getNickname()).as("check user Nickname").isEqualTo(nickname);
```suggestion
        assertThat(dto.getLoginId()).isEqualTo(loginId)
                .as("check user ID");
```

`nit` 
개인적으로 이런 형태를 선호합니다.
단언문끼리 모으고, 설명은 별도 처리.

2022-09-16 05:16 UTC, Hyune-c approved these changes
try-catch 문을 더 적게 사용하는 방법을 고민해주세요.

2022-09-16 05:16 UTC, Hyune-c commented on server/mainPr/src/main/java/com/team23/mainPr/Login/Service/LoginService.java
> +            if (member != null) {
null 처리를 좀 더 잘 할 수 있는 방법이 있을 것 같습니다.

2022-09-16 05:16 UTC, Hyune-c commented on server/mainPr/src/main/java/com/team23/mainPr/MainPrApplication.java
> +    }    public static final ZoneId DEFAULT_TIME_ZONE = ASIA_SEOUL.getZoneId();
- 개행이 잘못된 것 같습니다.

`nit`
- 보통 이런 값은 별도의 constant 형태로 관리하는 것 같아요.
- 또는 yml 에서 관리합니다.

2022-09-16 05:16 UTC, Hyune-c commented on server/mainPr/src/main/java/com/team23/mainPr/RentPost/Service/RentPostService.java
> + */
<img width="722" alt="image" src="https://user-images.githubusercontent.com/55722186/190561563-75b09a2e-9901-479b-8e18-40b1f2808355.png">

`nit`

javadoc 을 사용시 intellij 에서는 좀 더 가독성이 좋은 형태로 변환해줍니다.
하지만 지금의 주석들은 intellij 변환시 개행이 의도한대로 들어가지 않고 있네요.

2022-09-16 10:26 UTC, merged